PUT http://localhost:8080/update-password?token=06fe6144-b230-498b-8b62-7584bd5d879c
Content-Type: application/json
Accept: application/json

{
    "password_new": "123456789",
    "password_confirmation": "123456789"
}
